CREATE TABLE CAR_READINGS(
   ID            INTEGER PRIMARY KEY NOT NULL,
   EVENTTIME     TEXT    NOT NULL,
   DEVICEDATA    BLOB    NOT NULL
);

CREATE TABLE LAST_PROCESSED(
    TABLE_NAME         TEXT NOT NULL,
    LAST_PROCESSED_ID  INTEGER NOT NULL
);

CREATE TABLE PROCESSED_READINGS(
    ID          INTEGER PRIMARY KEY NOT NULL,
    EVENTTIME   TEXT NOT NULL,
    TRANSMITTED BOOLEAN DEFAULT FALSE,
    DEVICEDATA  BLOB NOT NULL,
    ENCKEY  BLOB NOT NULL,
    DATASIZE INTEGER NOT NULL
);
